services:
    apache:
        image: bitnami/apache:latest
        container_name: apache
        ports:
            - 80:8080
            - 443:8443
        volumes:
            - ./app:/usr/local/apache2/htdocs